package com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling;

import java.lang.annotation.Annotation;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.Date;

@DynamoDBAutoGenerated(generator=Generator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({java.lang.annotation.ElementType.FIELD, java.lang.annotation.ElementType.METHOD})
public @interface DynamoDBAutoGeneratedTimestamp
{
  DynamoDBAutoGenerateStrategy strategy() default DynamoDBAutoGenerateStrategy.ALWAYS;
  
  public static final class Generator<T>
    extends DynamoDBAutoGenerator.AbstractGenerator<T>
  {
    private final DynamoDBTypeConverter<T, Date> converter;
    
    public Generator(Class<T> targetType, DynamoDBAutoGeneratedTimestamp annotation)
    {
      super();
      converter = StandardTypeConverters.factory().getConverter(targetType, Date.class);
    }
    
    public final T generate(T currentValue)
    {
      return (T)converter.convert(new Date());
    }
  }
}

/* Location:
 * Qualified Name:     com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */