package com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling;

public final class DynamoDBAutoGeneratedDefault$Generator<T>
  extends DynamoDBAutoGenerator.AbstractGenerator<T>
{
  private final DynamoDBTypeConverter<T, String> converter;
  private final String defaultValue;
  
  public DynamoDBAutoGeneratedDefault$Generator(Class<T> targetType, DynamoDBAutoGeneratedDefault annotation)
  {
    super(DynamoDBAutoGenerateStrategy.CREATE);
    converter = StandardTypeConverters.factory().getConverter(targetType, String.class);
    defaultValue = annotation.value();
  }
  
  public final T generate(T currentValue)
  {
    return (T)converter.convert(defaultValue);
  }
}

/* Location:
 * Qualified Name:     com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedDefault.Generator
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */