package com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling;

import java.lang.annotation.Annotation;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.UUID;

@DynamoDB
@DynamoDBAutoGenerated(generator=Generator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({java.lang.annotation.ElementType.FIELD, java.lang.annotation.ElementType.METHOD, java.lang.annotation.ElementType.ANNOTATION_TYPE})
public @interface DynamoDBGeneratedUuid
{
  DynamoDBAutoGenerateStrategy value();
  
  public static final class Generator<T>
    extends DynamoDBAutoGenerator.AbstractGenerator<T>
  {
    private final DynamoDBTypeConverter<T, UUID> converter;
    
    public Generator(Class<T> targetType, DynamoDBGeneratedUuid annotation)
    {
      super();
      converter = StandardTypeConverters.factory().getConverter(targetType, UUID.class);
    }
    
    public final T generate(T currentValue)
    {
      return (T)converter.convert(UUID.randomUUID());
    }
  }
}

/* Location:
 * Qualified Name:     com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBGeneratedUuid
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */