package com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling;

import java.util.Date;

public final class DynamoDBAutoGeneratedTimestamp$Generator<T>
  extends DynamoDBAutoGenerator.AbstractGenerator<T>
{
  private final DynamoDBTypeConverter<T, Date> converter;
  
  public DynamoDBAutoGeneratedTimestamp$Generator(Class<T> targetType, DynamoDBAutoGeneratedTimestamp annotation)
  {
    super(annotation.strategy());
    converter = StandardTypeConverters.factory().getConverter(targetType, Date.class);
  }
  
  public final T generate(T currentValue)
  {
    return (T)converter.convert(new Date());
  }
}

/* Location:
 * Qualified Name:     com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp.Generator
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */