package com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling;

import java.lang.annotation.Annotation;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@DynamoDB
@DynamoDBAutoGenerated(generator=Generator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({java.lang.annotation.ElementType.FIELD, java.lang.annotation.ElementType.METHOD})
public @interface DynamoDBAutoGeneratedDefault
{
  String value();
  
  public static final class Generator<T>
    extends DynamoDBAutoGenerator.AbstractGenerator<T>
  {
    private final DynamoDBTypeConverter<T, String> converter;
    private final String defaultValue;
    
    public Generator(Class<T> targetType, DynamoDBAutoGeneratedDefault annotation)
    {
      super();
      converter = StandardTypeConverters.factory().getConverter(targetType, String.class);
      defaultValue = annotation.value();
    }
    
    public final T generate(T currentValue)
    {
      return (T)converter.convert(defaultValue);
    }
  }
}

/* Location:
 * Qualified Name:     com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedDefault
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */